<?php
if (isset($_COOKIE['language'])) {
    $code = $_COOKIE['language'];
} else {
    $code = 'EN';
}

switch ($code) {
    case 'VI':
        $_SESSION['welcome'] = 'Chào mừng';
        $_SESSION['home'] = 'Trang chủ';
        $_SESSION['about_us'] = 'Về chúng tôi';
        $_SESSION['gallery'] = 'Bộ sưu tập';
        $_SESSION['design_forum'] = 'Diễn đàn thiết kế';
        $_SESSION['contact'] = 'Liên hệ';
        $_SESSION['languages'] = 'Ngôn ngữ';
        $_SESSION['english'] = 'Tiếng Anh';
        $_SESSION['chinese'] = 'Trung Quốc';
        $_SESSION['bahasa'] = 'Bahasa';
        $_SESSION['japanese'] = 'Tiếng Nhật';
        $_SESSION['korean'] = 'Hàn Quốc';
        $_SESSION['myanmar'] = 'Myanmar';
        $_SESSION['vietnamese'] = 'Tiếng Việt';
        $_SESSION['music'] = 'NHẠC';
        $_SESSION['on'] = 'MỞ';
        $_SESSION['off'] = 'TẮT';
        $_SESSION['our_mission'] = 'Sứ mệnh của chúng tôi';
        $_SESSION['mission_content'] = 'Niềm tin của chúng tôi là không thứ gì có thể tồn tại độc lập trên thế giới này. Chúng ta tồn tại cùng nhau và hỗ trợ nhau phát triển, điều này giúp thế giới trở nên muôn màu muôn vẻ, rực rỡ hơn. Một sản phẩm tuyệt vời không chỉ được thiết kế đẹp, nó còn phải .... ';
        $_SESSION['our_story'] = 'Lịch sử của chúng tôi';
        $_SESSION['story_content'] = 'Empyrean Design được thành lập vào năm 1992 bởi Eric Haywood Chang. Sau khi tốt nghiệp trường đại học mỹ thuật LaSalle tại Singapo, ngành thiết kế nội thất và chuyên ngành thiết kế sản phẩm và mỹ thuật. Ông là một kiến trúc sư có nhiều năm kinh nghiệm trong lĩnh vực thiết kế. Ông đam mê thiết kế, nghệ thuật và âm nhạc...';
        $_SESSION['copyright'] = 'Copyright &copy; 2015 Empyrean Design. Tất cả những quyền được bảo lưu.';

        $_SESSION['about_our_mission'] = '<p> Niềm tin của chúng tôi là không thứ gì có thể tồn tại độc lập trên thế giới này. Chúng ta tồn tại cùng nhau và hỗ trợ nhau phát triển, điều này giúp thế giới trở nên muôn màu muôn vẻ, rực rỡ hơn. Một sản phẩm tuyệt vời không chỉ được thiết kế đẹp, nó còn phải có thể bán được. Chúng tôi tin rằng việc thiết kế có thể đem bán là thiết kế có đa năng nhất và hấp dẫn cho người tiêu dùng, ngoài khía cạnh thẩm mỹ. Chúng tôi đang ở phía trước của các xu hướng thiết kế, và trong thực tế, chúng ta dám tạo ra sự khác biệt trong quá trình tư duy. Chúng tôi rất quan trọng trong khái niệm thiết kế, chưa có khả năng cung cấp các giải pháp về lâu dài. Chúng tôi có biết làm thế nào trong việc tích hợp các thành phần và các vấn đề mà sẽ cung cấp các giải pháp toàn diện, thiết thực và kinh tế trong điều kiện hoạt động của nguồn nhân lực, chi phí vận hành và lợi nhuận. Một trong những mối quan tâm chính của chúng tôi là cung cấp một thiết kế xuất sắc mà còn trong việc bảo tồn các nguồn tài nguyên khách hàng. </ p> <p class = "center"> <strong> - Chúng ta dám đối mặt với những vấn đề tiêu cực, vì chúng ta sẽ có những giải pháp tích cực để khắc phục chúng. - <br> Trích dẫn Haywood Change của Eric </strong> </ p> <p> Công ty chúng tôi tin tưởng trong việc đóng góp cho xã hội và cho thế giới. Chúng tôi đang tích cực giúp đỡ các sinh viên trên toàn thế giới trong việc chia sẻ các thiết kế và các lời phê bình. Ngoài ra, chúng tôi đã thiết lập một diễn đàn thiết kế để tạo thuận lợi cho chức năng này. Chúng tôi muốn giúp các nhà lãnh đạo trẻ tương lai của chúng tôi thiết kế để ước mơ, khám phá, và ở lại đam mê trong những gì họ tin tưởng và yêu thương làm. <br> Trong việc hỗ trợ các ngành công nghiệp âm nhạc, chúng tôi cung cấp cho khách hàng lĩnh vực cạnh tranh chi phí cho các nghệ sĩ và có liên quan đặc biệt trong môi trường âm thanh xây dựng lên. <br> Chúng tôi cũng tham gia vào các chương trình cho thế giới thứ ba. </ p> <p class = "center"> Điều này gắn chặt với tầm nhìn của chúng tôi: <strong> Định hình tương lai chúng ta hôm nay </strong> </ p> <p> Chúng tôi đang định hình tương lai của chúng tôi bằng cách đầu tư và ảnh hưởng đến những người khác trong doanh nghiệp.<br> Dám ước mơ, biến những giấc mơ biến thành hiện thực. <br> Từ bản vẽ cho các tòa nhà, xây dựng một tương lai tốt đẹp. <br> Chúng tôi luôn tự tin bởi vì những khách hàng của chúng tôi tin tưởng vào giấc mơ chúng tôi. </ p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design được thành lập vào năm 1992 bởi Eric Haywood Chang. Sau khi tốt nghiệp trường đại học mỹ thuật LaSalle tại Singapo, ngành thiết kế nội thất và chuyên ngành thiết kế sản phẩm và mỹ thuật. Ông là một kiến trúc sư có nhiều năm kinh nghiệm trong lĩnh vực thiết kế. Ông đam mê thiết kế, nghệ thuật và âm nhạc. </p> <p> Từ ngày đầu tiên, tập trung chính của chúng tôi đã được trong thiết kế nội thất. Chúng tôi đã hoàn thành nhiều dự án, từ dân cư cho các khách hàng của công ty. Sức mạnh cốt lõi của chúng tôi luôn luôn là trong lĩnh vực xác định hình ảnh của khách hàng và nhu cầu của họ trong suốt quá trình thiết kế của chúng tôi. Chúng tôi có khả năng phát triển hình ảnh của công ty mới và hiện tại cho phần khởi động của công ty mới cũng như cho các công ty đang tìm kiếm vào việc thay đổi hình ảnh công ty của họ. Khách hàng của chúng tôi từ bán lẻ, các công ty doanh nghiệp, khách sạn, cho các cơ quan chính phủ. Chúng tôi đi qua toàn bộ quá trình thiết kế với khách hàng của chúng tôi từ mặt đất bằng không để hoàn thành của từng dự án. Chúng tôi làm việc chặt chẽ với đội ngũ chuyên dụng của chúng ta về kiến trúc, thiết kế, kỹ sư chuyên nghiệp, và các nhà thầu dưới cánh của chúng tôi. Chúng tôi có thể tùy chỉnh phạm vi của chúng tôi làm việc theo yêu cầu của khách hàng từ giai đoạn thiết kế, quản lý dự án, giai đoạn xây dựng và bàn giao dự án cho khách hàng. </ p> <p> Kể từ năm 2004, do các kết nối mạnh mẽ của chúng tôi ở Trung Quốc, chúng tôi đã phân nhánh vào kiến trúc từ thiết kế nội thất. Chúng tôi đã có sự hợp tác hiệu quả với nhiều đối tác Trung Quốc của chúng tôi tại các tỉnh của Trung Quốc và các thành phố khác nhau. Tuy nhiên, tâm điểm chính của chúng tôi đã được ở tỉnh Hải Nam do nó có những con số cao nhất của khách sạn và khu nghỉ dưỡng; các "Hawaii của Trung Quốc" như nhiều người đã đặt tên. Gần đây, chúng tôi đã khảo sát các trang web với mục tiêu giả lập cho kiểm tra kỹ lưỡng hơn và giới thiệu các trang web là tối ưu cho khách hàng sử dụng của chúng tôi. </ p> <p> Trong năm 2008, chúng tôi mạo hiểm vào chuyên môn của môi trường âm thanh cho dù đó là để hỗ trợ các nghệ sĩ hay kỹ sư âm thanh trong khu vực. Sau đó, chúng tôi liên quan đến mình trong việc thiết kế và xây dựng các môi trường khác nhau, từ không gian trung tâm casino, phạm vi bắn trong nhà, giảng đường, thu âm studio, phòng phát thanh truyền hình, nhà hát, vv </ p> <p> Trong năm 2014, chúng tôi bước vào thị trường Myanmar. Chúng tôi đang từ từ đà trong việc thiết kế & xây dựng các ngành công nghiệp. </ p>';

        $_SESSION['lblFullName']  = 'Tên đầy đủ';
        $_SESSION['lblEmail']  = 'EMAIL';
        $_SESSION['lblSchool']  = 'Tên trường';
        $_SESSION['lblFaculty']  = 'Khoa';
        $_SESSION['lblYearStarted']  = 'Năm bắt đầu';
        $_SESSION['lblAspiration']  = "Khát vọng hiện tại hoặc tương lai của bạn ?";
        $_SESSION['lblSend']  = 'Gửi';

        $_SESSION['forumdesign_objective_label'] = "Diễn đàn thiết kế cho học sinh quốc tế";
        $_SESSION['forumdesign_objective_content'] = "<p> Mục tiêu của diễn đàn thiết kế là để giúp xây dựng sự tự tin của học sinh trong thiết kế. <br> Chúng tôi sẽ giúp họ nhìn thấy những thế giới vật lý trong một lĩnh vực mới để có thiết kế ý thức hơn trong việc giải quyết vấn đề. <br> Họ sẽ tìm hiểu thông qua các quan điểm vĩ mô và vi mô của các thành phần, do đó mở rộng quan điểm của họ về nhận thức trong họ khái niệm thiết kế. </p> <p class = 'center'> <strong> - Khi người ta không thể nhìn thấy xa hơn kích thước của cuộc sống, không có gì có lợi nhuận có thể được tạo ra. - <br> Trích dẫn Haywood Change của Eric</strong> </p> <p> Khi đăng ký với chúng tôi, học sinh từ bất kỳ giảng viên thiết kế có thể gửi tác phẩm của mình cho các nhà phê bình thiết kế hoặc để thảo luận <br> Trong trở lại, chúng tôi sẽ đăng lên. các công trình (sau khi có sự chấp thuận của cá nhân học sinh) để chia sẻ để nhiều có thể học và hưởng lợi từ nó. </p>";
        break;

    case 'BA':
        $_SESSION['welcome'] = 'Sambutan';
        $_SESSION['home'] = 'Rumah';
        $_SESSION['about_us'] = 'Tentang Kami';
        $_SESSION['gallery'] = 'Galeri';
        $_SESSION['design_forum'] = 'Desain Forum';
        $_SESSION['contact'] = 'Kontak';
        $_SESSION['languages'] = 'Bahasa';
        $_SESSION['english'] = 'Inggris';
        $_SESSION['chinese'] = 'Cina';
        $_SESSION['bahasa'] = 'Bahasa';
        $_SESSION['japanese'] = 'Jepang';
        $_SESSION['korean'] = 'Korea';
        $_SESSION['myanmar'] = 'Myanmar';
        $_SESSION['vietnamese'] = 'Orang Vietnam';
        $_SESSION['music'] = 'MUSIK';
        $_SESSION['on'] = 'PADA';
        $_SESSION['off'] = 'LEPAS';
        $_SESSION['our_mission'] = 'Misi kita';
        $_SESSION['mission_content'] = 'Kami mempercayai bahwa tidak ada sesuatu yang terbentuk dengan sendirinya didunia ini. Kita berkerja berdampingan dan saling bergantung satu dan lainnya. Hal ini menciptakan dimensi yang lebih besar dan memberikan corak pada dunia. Disain yang bagus tidak cukup, produk yang luar biasa akan memiliki nilai jual tersendiri. Kami mempercayai bahwa disamping memiliki aspek estetis...';
        $_SESSION['our_story'] = 'Latar Belakang';
        $_SESSION['story_content'] = 'EMPYREAN DESIGN  didirikan oleh Eric Haywood Chang pada tahun 1992. Menyelesaikan pendidikan  di LaSalle College of the Arts di Singapore dalam bidang Interior Designing and minor in Product Designing and Fine Arts. Eric Haywood Chang adalah arsitek yang sangat handal dan memiliki pengalaman beberapa tahun dan ahli dalam bidangnya. Dia menguasai  bidang disain, seni dan musik...';
        $_SESSION['copyright'] = '';

        $_SESSION['about_our_mission'] = '<p> It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer, besides the aesthetic aspect. We are ahead of design trends, and in fact, trend setters because we dare to be different in our thinking process. We are critical in design concepts, yet able to provide long terms solutions. We possess the know how in integrating components and issues that will provide comprehensive, practical and economic solutions in terms of operations of human resources, operating cost, and profit. One of our main concern is in providing an outstanding design but also in the preservation of our clients resources as well. </p> <p class="center"> <strong> - We dare to face the negative issues, for we will have the positive solutions to overcome them. - <br> Eric\'s Haywood Chang\'s quote </strong> </p> <p> Our company believes in giving back to the society and to the world. We are actively helping students around the world in sharing designs and critics. In addition, we have setup a design forum to facilitate this function. We wish to help our future young design leaders to dream, explore, and stay passionate in what they believe in and love doing. <br> In supporting the music industries, we provide special competitive costing for artistes and related field clients in the acoustic environment build up. <br> We are also involved in the feeding the third world program. </p> <p class="center"> This ties in with our vision: <strong>Shaping our future today</strong> </p> <p> We are shaping our future by investing and impacting in others now. <br> Dare to dream, turning dreams into reality. <br> From drawings to buildings, building a better tomorrow.<br> We are who we are now because our clients believes in our dreams. </p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music. </p> <p> From day one, our main focus has been in interior designing. We have completed many projects, ranging from residential to corporate clients. Our core strength has always been in the area of identifying our clients\' image and their needs during our design process. We are capable of developing new and current corporate images for new company startups as well as for companies that are looking into changing their corporate image. Our clients range from retail, corporate companies, hospitality, to government agencies. We walk through the entire design process with our clients from the ground zero to the completion of each projects. We work closely with our dedicated team of architectures, designers, professional engineers, and contractors under our wing. We are able to customize our scope of work as per our client\'s requirement from design stage, project management, construction stage and to handing over of project to our client. </p> <p> Since 2004, due to our strong connections in China, we have branched into architecture from interior designing. We have had fruitful cooperation with many of our China counterparts in different cities and provinces of China. However, our main focal point has been in the Hainan Province due to it having the highest numbers of hotels and resorts; the "Hawaii of China" as many have named. Recently, we have surveyed sites with drones for a more thorough inspection and recommend the sites which are optimal for our clients usage. </p> <p> In 2008, we ventured into the specialization of acoustic environments whether it be for supporting artistes or sound engineers in the region. Thereafter, we involved ourselves in the designing and building up of different environments, from casino gaming spaces, indoor firing ranges, lecture halls, recording studios, broadcasting rooms, home theatres, etc. </p> <p> In 2014, we entered Myanmar market. We are slowly gaining momentum in the design & construction industries. </p>';
        break;

    case 'JP':
        $_SESSION['welcome'] = 'ようこそ';
        $_SESSION['home'] = 'ホーム';
        $_SESSION['about_us'] = '私たちに関しては';
        $_SESSION['gallery'] = 'ギャラリー';
        $_SESSION['design_forum'] = 'デザインフォーラム';
        $_SESSION['contact'] = 'コンタクト';
        $_SESSION['languages'] = '言語';
        $_SESSION['english'] = '英語';
        $_SESSION['chinese'] = '中国の';
        $_SESSION['bahasa'] = 'バハサ';
        $_SESSION['japanese'] = '日本語';
        $_SESSION['korean'] = '韓国語';
        $_SESSION['myanmar'] = 'ミャンマー';
        $_SESSION['vietnamese'] = 'ベトナム語';
        $_SESSION['music'] = '音楽';
        $_SESSION['on'] = 'オン';
        $_SESSION['off'] = 'オフ';
        $_SESSION['our_mission'] = '我々の使命';
        $_SESSION['mission_content'] = '私たちは、何もこの世界では、それ自体によって形成されていないと信じています。私たちは並んで動作し、互いに相互に依存しています。これは、より大きな寸法を作成し、世界にスタイルを与えます。グッドデザインは、優れた製品は、独自のセールスポイントを持っていますが、十分ではありません。。。';
        $_SESSION['our_story'] = '私たちの物語';
        $_SESSION['story_content'] = '荘厳なデザインは、製品のデザインと美術におけるインテリアデザインの分野とマイナーにシンガポールで芸術のラサール大学で卒業、1992年にエリック・ヘイウッドチャンによって設立されました。エリック・ヘイウッドの建築家チャンは、非常に信頼性が高いと、数年の経験を持ち、それぞれの分野の専門家です。。。';
        $_SESSION['copyright'] = '';

        $_SESSION['about_our_mission'] = '<p> It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer, besides the aesthetic aspect. We are ahead of design trends, and in fact, trend setters because we dare to be different in our thinking process. We are critical in design concepts, yet able to provide long terms solutions. We possess the know how in integrating components and issues that will provide comprehensive, practical and economic solutions in terms of operations of human resources, operating cost, and profit. One of our main concern is in providing an outstanding design but also in the preservation of our clients resources as well. </p> <p class="center"> <strong> - We dare to face the negative issues, for we will have the positive solutions to overcome them. - <br> Eric\'s Haywood Chang\'s quote </strong> </p> <p> Our company believes in giving back to the society and to the world. We are actively helping students around the world in sharing designs and critics. In addition, we have setup a design forum to facilitate this function. We wish to help our future young design leaders to dream, explore, and stay passionate in what they believe in and love doing. <br> In supporting the music industries, we provide special competitive costing for artistes and related field clients in the acoustic environment build up. <br> We are also involved in the feeding the third world program. </p> <p class="center"> This ties in with our vision: <strong>Shaping our future today</strong> </p> <p> We are shaping our future by investing and impacting in others now. <br> Dare to dream, turning dreams into reality. <br> From drawings to buildings, building a better tomorrow.<br> We are who we are now because our clients believes in our dreams. </p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music. </p> <p> From day one, our main focus has been in interior designing. We have completed many projects, ranging from residential to corporate clients. Our core strength has always been in the area of identifying our clients\' image and their needs during our design process. We are capable of developing new and current corporate images for new company startups as well as for companies that are looking into changing their corporate image. Our clients range from retail, corporate companies, hospitality, to government agencies. We walk through the entire design process with our clients from the ground zero to the completion of each projects. We work closely with our dedicated team of architectures, designers, professional engineers, and contractors under our wing. We are able to customize our scope of work as per our client\'s requirement from design stage, project management, construction stage and to handing over of project to our client. </p> <p> Since 2004, due to our strong connections in China, we have branched into architecture from interior designing. We have had fruitful cooperation with many of our China counterparts in different cities and provinces of China. However, our main focal point has been in the Hainan Province due to it having the highest numbers of hotels and resorts; the "Hawaii of China" as many have named. Recently, we have surveyed sites with drones for a more thorough inspection and recommend the sites which are optimal for our clients usage. </p> <p> In 2008, we ventured into the specialization of acoustic environments whether it be for supporting artistes or sound engineers in the region. Thereafter, we involved ourselves in the designing and building up of different environments, from casino gaming spaces, indoor firing ranges, lecture halls, recording studios, broadcasting rooms, home theatres, etc. </p> <p> In 2014, we entered Myanmar market. We are slowly gaining momentum in the design & construction industries. </p>';
        break;

    case 'KO':
        $_SESSION['welcome'] = '환영';
        $_SESSION['home'] = '집';
        $_SESSION['about_us'] = '회사 소개';
        $_SESSION['gallery'] = '갤러리';
        $_SESSION['design_forum'] = '디자인 포럼';
        $_SESSION['contact'] = '접촉';
        $_SESSION['languages'] = '언어';
        $_SESSION['english'] = '영어';
        $_SESSION['chinese'] = '중국어';
        $_SESSION['bahasa'] = '한국어';
        $_SESSION['japanese'] = '일본의';
        $_SESSION['korean'] = '한국어';
        $_SESSION['myanmar'] = '미얀마';
        $_SESSION['vietnamese'] = '베트남의';
        $_SESSION['music'] = '음악';
        $_SESSION['on'] = '에';
        $_SESSION['off'] = '해제';
        $_SESSION['our_mission'] = '우리의 미션';
        $_SESSION['mission_content'] = '그것은 아무것도이 세상에서 그 자체로 존재하지 않음을 우리의 믿음이다. 우리는 공존 서로 우리는 서로에 상호 의존적이다. 이것은 더 큰 치수를 작성하고 땅에 색상을 기여한다. 좋은 디자인은 충분하지 않습니다; 좋은 제품 자체를 판매 할 수있을 것입니다. 우리가 판매하는 디자인은 미적 측면 외에...';
        $_SESSION['our_story'] = '우리의 이야기';
        $_SESSION['story_content'] = 'Empyrean Design 은 Eric Haywood Chang 에 의해 1992 년에 설립되었다.싱가포르 예술의 LaSalle 대학을 졸업 한; 인테리어 디자인 전공 및 제품 디자인 및 미술에 작은, 그는 관련 분야에서 경험과 전문 지식의 많은 년을 가지고 독학으로 건축가입니다. 그는 디자인, 예술, 음악에 대한 열정이다...';
        $_SESSION['copyright'] = '';

        $_SESSION['about_our_mission'] = '<p> It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer, besides the aesthetic aspect. We are ahead of design trends, and in fact, trend setters because we dare to be different in our thinking process. We are critical in design concepts, yet able to provide long terms solutions. We possess the know how in integrating components and issues that will provide comprehensive, practical and economic solutions in terms of operations of human resources, operating cost, and profit. One of our main concern is in providing an outstanding design but also in the preservation of our clients resources as well. </p> <p class="center"> <strong> - We dare to face the negative issues, for we will have the positive solutions to overcome them. - <br> Eric\'s Haywood Chang\'s quote </strong> </p> <p> Our company believes in giving back to the society and to the world. We are actively helping students around the world in sharing designs and critics. In addition, we have setup a design forum to facilitate this function. We wish to help our future young design leaders to dream, explore, and stay passionate in what they believe in and love doing. <br> In supporting the music industries, we provide special competitive costing for artistes and related field clients in the acoustic environment build up. <br> We are also involved in the feeding the third world program. </p> <p class="center"> This ties in with our vision: <strong>Shaping our future today</strong> </p> <p> We are shaping our future by investing and impacting in others now. <br> Dare to dream, turning dreams into reality. <br> From drawings to buildings, building a better tomorrow.<br> We are who we are now because our clients believes in our dreams. </p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music. </p> <p> From day one, our main focus has been in interior designing. We have completed many projects, ranging from residential to corporate clients. Our core strength has always been in the area of identifying our clients\' image and their needs during our design process. We are capable of developing new and current corporate images for new company startups as well as for companies that are looking into changing their corporate image. Our clients range from retail, corporate companies, hospitality, to government agencies. We walk through the entire design process with our clients from the ground zero to the completion of each projects. We work closely with our dedicated team of architectures, designers, professional engineers, and contractors under our wing. We are able to customize our scope of work as per our client\'s requirement from design stage, project management, construction stage and to handing over of project to our client. </p> <p> Since 2004, due to our strong connections in China, we have branched into architecture from interior designing. We have had fruitful cooperation with many of our China counterparts in different cities and provinces of China. However, our main focal point has been in the Hainan Province due to it having the highest numbers of hotels and resorts; the "Hawaii of China" as many have named. Recently, we have surveyed sites with drones for a more thorough inspection and recommend the sites which are optimal for our clients usage. </p> <p> In 2008, we ventured into the specialization of acoustic environments whether it be for supporting artistes or sound engineers in the region. Thereafter, we involved ourselves in the designing and building up of different environments, from casino gaming spaces, indoor firing ranges, lecture halls, recording studios, broadcasting rooms, home theatres, etc. </p> <p> In 2014, we entered Myanmar market. We are slowly gaining momentum in the design & construction industries. </p>';
        break;

    case 'MY':
        $_SESSION['welcome'] = 'ကြိုဆို';
        $_SESSION['home'] = 'နေအိမ်';
        $_SESSION['about_us'] = 'ကြှနျုပျတို့အကွောငျး';
        $_SESSION['gallery'] = 'ဓာတ်ပုံပြခန်း';
        $_SESSION['design_forum'] = 'ဒီဇိုင်းကိုဖိုရမ်၏';
        $_SESSION['contact'] = 'ဆက်သွယ်ရန်';
        $_SESSION['languages'] = 'ဘာသာစကားများကို';
        $_SESSION['english'] = 'အင်္ဂလိပ်';
        $_SESSION['chinese'] = 'တရုတ်';
        $_SESSION['bahasa'] = 'Bahasa';
        $_SESSION['japanese'] = 'ဂျပန်';
        $_SESSION['korean'] = 'ကိုရီးယား';
        $_SESSION['myanmar'] = 'မြန်မာ';
        $_SESSION['vietnamese'] = 'ဗီယက်နမ်';
        $_SESSION['music'] = 'တေးဂီတ';
        $_SESSION['on'] = 'အပေါ်';
        $_SESSION['off'] = 'ချွတ်';
        $_SESSION['our_mission'] = 'ရည္ရြယ္ခ်က္';
        $_SESSION['mission_content'] = 'ေလာကတြင္ မည္သည့္အရာမွ သီးျခားရပ္တည္ နိုင္စြမ္းမရွိ ဟူေသာစကားကို ကြၽန္ုပ္တို႔ ယံုၾကည္ပါသည္။ ကြၽနု္ပ္တို႔သည္ အတူတကြ ပူးေပါင္း ေနထုိင္ျပီး တစ္ဦးႏွင့္ တစ္ဦး အျပန္အလွန္ အမွီသဟဲ ျပဳေနၾကရပါသည္။ ယင္းသို႔ အတူတကြ ပူးေပါင္းေနထုိင္ျခင္းသည္ ကမာၻေျမၾကီးကို ပိုမိုသာယာလွပျပီး အဓိပၸာယ္ ရွိေစသည္။ ပစၥည္းေကာင္းတို႔မည္သည္မွာ တျခားမည့္သည့္ အတြဲအစပ္မွ မပါပဲ သူ႔အတုိင္းကိုပင္ ေရာင္းခ်နိုင္စြမ္း ရွိၾကသည္။ ေရာင္းခ်၍ရေသာ ဒီဇိုင္းမ်ားသည္ သံုးစြဲသူမ်ား အထူးနွစ္သက္ သေဘာက် နွစ္ခ်ိဳက္ျပီး ၀ယ္သူ၏ လိုအပ္ခ်က္မ်ားနွင့္ ကိုက္ညီ၍ သာ ေရာင္းခ်နုိင္ျခင္းျဖစ္သည္ ဟုလည္း...';
        $_SESSION['our_story'] = 'ကုမၸဏီအေၾကာင္း';
        $_SESSION['story_content'] = 'ကြၽနု္ပ္တို႔၏ Empyrean Design ကုမၸဏီကို ၁၉၉၂ ခုနွစ္တြင္ Mr. Eric Haywood Chang မွ စတင္တည္ေထာင္ခဲ့ ပါသည္။ Mr. Eric သည္ Singapore နိုင္ငံ LaSalle College of the Arts မွ ဘြဲ႔ရရွိခဲ့ျပီး သူ၏ အဓိကဘာသာရပ္မ်ားမွာ အိမ္တြင္းအလွ ဆင္လုပ္ငန္းျဖစ္ျပီး အရန္ဘာသာရပ္မ်ားအျဖစ္ ကုန္ပစၥည္း ဒီဇိုင္းထြင္ျခင္းနွင့္ အျခားလက္မႈ အနုပညာမ်ား ပါ၀င္ပါသည္။ သူသည္ အေဆာက္အဦနွင့္ ပတ္သတ္ေသာ ဗိသုကာပညာကို ကိုယ္တိုင္ အပတ္တကုတ္ၾကိုစား သင္ယူခဲ့ရျပီး ၄င္းပညာျဖင့္ပင္ နွစ္ေပါင္းမ်ားစြာ လုပ္ကိုင္ခဲ့ျခင္းမွ အေတြ႔အၾကံု ဗဟုသုတမ်ားစြာ ရရွိျပီး ကြၽမ္းက်င္သူ တစ္ေယာက္ျဖစ္လာ ခဲ့ပါသည္။ သူသည္ ဂီတ၊ အႏုပညာ နွင့္ ဒီဇိုင္းဖန္တီးျခင္း...';
        $_SESSION['copyright'] = '';

        $_SESSION['about_our_mission'] = '<p> It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer, besides the aesthetic aspect. We are ahead of design trends, and in fact, trend setters because we dare to be different in our thinking process. We are critical in design concepts, yet able to provide long terms solutions. We possess the know how in integrating components and issues that will provide comprehensive, practical and economic solutions in terms of operations of human resources, operating cost, and profit. One of our main concern is in providing an outstanding design but also in the preservation of our clients resources as well. </p> <p class="center"> <strong> - We dare to face the negative issues, for we will have the positive solutions to overcome them. - <br> Eric\'s Haywood Chang\'s quote </strong> </p> <p> Our company believes in giving back to the society and to the world. We are actively helping students around the world in sharing designs and critics. In addition, we have setup a design forum to facilitate this function. We wish to help our future young design leaders to dream, explore, and stay passionate in what they believe in and love doing. <br> In supporting the music industries, we provide special competitive costing for artistes and related field clients in the acoustic environment build up. <br> We are also involved in the feeding the third world program. </p> <p class="center"> This ties in with our vision: <strong>Shaping our future today</strong> </p> <p> We are shaping our future by investing and impacting in others now. <br> Dare to dream, turning dreams into reality. <br> From drawings to buildings, building a better tomorrow.<br> We are who we are now because our clients believes in our dreams. </p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music. </p> <p> From day one, our main focus has been in interior designing. We have completed many projects, ranging from residential to corporate clients. Our core strength has always been in the area of identifying our clients\' image and their needs during our design process. We are capable of developing new and current corporate images for new company startups as well as for companies that are looking into changing their corporate image. Our clients range from retail, corporate companies, hospitality, to government agencies. We walk through the entire design process with our clients from the ground zero to the completion of each projects. We work closely with our dedicated team of architectures, designers, professional engineers, and contractors under our wing. We are able to customize our scope of work as per our client\'s requirement from design stage, project management, construction stage and to handing over of project to our client. </p> <p> Since 2004, due to our strong connections in China, we have branched into architecture from interior designing. We have had fruitful cooperation with many of our China counterparts in different cities and provinces of China. However, our main focal point has been in the Hainan Province due to it having the highest numbers of hotels and resorts; the "Hawaii of China" as many have named. Recently, we have surveyed sites with drones for a more thorough inspection and recommend the sites which are optimal for our clients usage. </p> <p> In 2008, we ventured into the specialization of acoustic environments whether it be for supporting artistes or sound engineers in the region. Thereafter, we involved ourselves in the designing and building up of different environments, from casino gaming spaces, indoor firing ranges, lecture halls, recording studios, broadcasting rooms, home theatres, etc. </p> <p> In 2014, we entered Myanmar market. We are slowly gaining momentum in the design & construction industries. </p>';
        break;

    case 'CN':
        $_SESSION['welcome'] = '歡迎';
        $_SESSION['home'] = '主頁';
        $_SESSION['about_us'] = '关于';
        $_SESSION['gallery'] = '画廊';
        $_SESSION['design_forum'] = '设计论坛';
        $_SESSION['contact'] = '联系我们';
        $_SESSION['languages'] = '語言';
        $_SESSION['english'] = '英語';
        $_SESSION['chinese'] = '中國';
        $_SESSION['bahasa'] = '印度尼西亞語';
        $_SESSION['japanese'] = '日本';
        $_SESSION['korean'] = '朝鮮的';
        $_SESSION['myanmar'] = '緬甸';
        $_SESSION['vietnamese'] = '越南';
        $_SESSION['music'] = '音樂';
        $_SESSION['on'] = '上';
        $_SESSION['off'] = '關閉';
        $_SESSION['our_mission'] = '使命宣言';
        $_SESSION['mission_content'] = '我们相信，在这个世界上没有什么存在本身。我们共存彼此和我们是相互依赖上彼此。这造成一个更美好，并有助于颜色的世界。良好的设计是不够;一个伟大的产品是一个就能卖自己。我们认为，销售的设计是最相关，并呼吁消费者。。。';
        $_SESSION['our_story'] = '我们的故事';
        $_SESSION['story_content'] = '恩碧亚设计公司(Empyrean Design)成立于1992年由郑杰明先生。从艺术中新加坡拉萨尔学院已经毕业;主修室内设计和较小的产品设计和美术，他也是一位自学成才的建筑设计师是拥有多年相关领域的经验和专业知识。他热衷于设计，艺术和音乐。。。';
        $_SESSION['copyright'] = '';

        $_SESSION['about_our_mission'] = '<p> It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer, besides the aesthetic aspect. We are ahead of design trends, and in fact, trend setters because we dare to be different in our thinking process. We are critical in design concepts, yet able to provide long terms solutions. We possess the know how in integrating components and issues that will provide comprehensive, practical and economic solutions in terms of operations of human resources, operating cost, and profit. One of our main concern is in providing an outstanding design but also in the preservation of our clients resources as well. </p> <p class="center"> <strong> - We dare to face the negative issues, for we will have the positive solutions to overcome them. - <br> Eric\'s Haywood Chang\'s quote </strong> </p> <p> Our company believes in giving back to the society and to the world. We are actively helping students around the world in sharing designs and critics. In addition, we have setup a design forum to facilitate this function. We wish to help our future young design leaders to dream, explore, and stay passionate in what they believe in and love doing. <br> In supporting the music industries, we provide special competitive costing for artistes and related field clients in the acoustic environment build up. <br> We are also involved in the feeding the third world program. </p> <p class="center"> This ties in with our vision: <strong>Shaping our future today</strong> </p> <p> We are shaping our future by investing and impacting in others now. <br> Dare to dream, turning dreams into reality. <br> From drawings to buildings, building a better tomorrow.<br> We are who we are now because our clients believes in our dreams. </p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music. </p> <p> From day one, our main focus has been in interior designing. We have completed many projects, ranging from residential to corporate clients. Our core strength has always been in the area of identifying our clients\' image and their needs during our design process. We are capable of developing new and current corporate images for new company startups as well as for companies that are looking into changing their corporate image. Our clients range from retail, corporate companies, hospitality, to government agencies. We walk through the entire design process with our clients from the ground zero to the completion of each projects. We work closely with our dedicated team of architectures, designers, professional engineers, and contractors under our wing. We are able to customize our scope of work as per our client\'s requirement from design stage, project management, construction stage and to handing over of project to our client. </p> <p> Since 2004, due to our strong connections in China, we have branched into architecture from interior designing. We have had fruitful cooperation with many of our China counterparts in different cities and provinces of China. However, our main focal point has been in the Hainan Province due to it having the highest numbers of hotels and resorts; the "Hawaii of China" as many have named. Recently, we have surveyed sites with drones for a more thorough inspection and recommend the sites which are optimal for our clients usage. </p> <p> In 2008, we ventured into the specialization of acoustic environments whether it be for supporting artistes or sound engineers in the region. Thereafter, we involved ourselves in the designing and building up of different environments, from casino gaming spaces, indoor firing ranges, lecture halls, recording studios, broadcasting rooms, home theatres, etc. </p> <p> In 2014, we entered Myanmar market. We are slowly gaining momentum in the design & construction industries. </p>';
        break;
    
    default:
        $_SESSION['welcome'] = 'Welcome';
        $_SESSION['home'] = 'Home';
        $_SESSION['about_us'] = 'About Us';
        $_SESSION['gallery'] = 'Gallery';
        $_SESSION['design_forum'] = 'Design Forum';
        $_SESSION['contact'] = 'Contact';
        $_SESSION['languages'] = 'Languages';
        $_SESSION['english'] = 'English';
        $_SESSION['chinese'] = 'Chinese';
        $_SESSION['bahasa'] = 'Bahasa';
        $_SESSION['japanese'] = 'Japanese';
        $_SESSION['korean'] = 'Korean';
        $_SESSION['myanmar'] = 'Myanmar';
        $_SESSION['vietnamese'] = 'Vietnamese';
        $_SESSION['music'] = 'MUSIC';
        $_SESSION['on'] = 'ON';
        $_SESSION['off'] = 'OFF';
        $_SESSION['our_mission'] = 'Our Mission';
        $_SESSION['mission_content'] = 'It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer...';
        $_SESSION['our_story'] = 'Our Story';
        $_SESSION['story_content'] = 'Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music...';
        $_SESSION['copyright'] = 'Copyright &copy; 2015 Empyrean Design. All rights reserved.';

        $_SESSION['about_our_mission'] = '<p> It is our belief that nothing exists by itself in this world. We co-exist with one another and we are interdependent on one another. This creates greater dimension and contributes colours to the earth. Good designs are not good enough; a great product is one that will be able to sell itself. We believe that the design that sells is the design that is most relevant and appealing to the consumer, besides the aesthetic aspect. We are ahead of design trends, and in fact, trend setters because we dare to be different in our thinking process. We are critical in design concepts, yet able to provide long terms solutions. We possess the know how in integrating components and issues that will provide comprehensive, practical and economic solutions in terms of operations of human resources, operating cost, and profit. One of our main concern is in providing an outstanding design but also in the preservation of our clients resources as well. </p> <p class="center"> <strong> - We dare to face the negative issues, for we will have the positive solutions to overcome them. - <br> Eric\'s Haywood Chang\'s quote </strong> </p> <p> Our company believes in giving back to the society and to the world. We are actively helping students around the world in sharing designs and critics. In addition, we have setup a design forum to facilitate this function. We wish to help our future young design leaders to dream, explore, and stay passionate in what they believe in and love doing. <br> In supporting the music industries, we provide special competitive costing for artistes and related field clients in the acoustic environment build up. <br> We are also involved in the feeding the third world program. </p> <p class="center"> This ties in with our vision: <strong>Shaping our future today</strong> </p> <p> We are shaping our future by investing and impacting in others now. <br> Dare to dream, turning dreams into reality. <br> From drawings to buildings, building a better tomorrow.<br> We are who we are now because our clients believes in our dreams. </p>';
        $_SESSION['about_our_story'] = '<p> Empyrean Design was founded in 1992 by Eric Haywood Chang. Having graduated from LaSalle College of the Arts in Singapore; majoring in Interior Designing and minor in Product Designing and Fine Arts, he is a self-taught architect that possesses many years of experience and expertise in the related field. He is passionate about design, arts, and music. </p> <p> From day one, our main focus has been in interior designing. We have completed many projects, ranging from residential to corporate clients. Our core strength has always been in the area of identifying our clients\' image and their needs during our design process. We are capable of developing new and current corporate images for new company startups as well as for companies that are looking into changing their corporate image. Our clients range from retail, corporate companies, hospitality, to government agencies. We walk through the entire design process with our clients from the ground zero to the completion of each projects. We work closely with our dedicated team of architectures, designers, professional engineers, and contractors under our wing. We are able to customize our scope of work as per our client\'s requirement from design stage, project management, construction stage and to handing over of project to our client. </p> <p> Since 2004, due to our strong connections in China, we have branched into architecture from interior designing. We have had fruitful cooperation with many of our China counterparts in different cities and provinces of China. However, our main focal point has been in the Hainan Province due to it having the highest numbers of hotels and resorts; the "Hawaii of China" as many have named. Recently, we have surveyed sites with drones for a more thorough inspection and recommend the sites which are optimal for our clients usage. </p> <p> In 2008, we ventured into the specialization of acoustic environments whether it be for supporting artistes or sound engineers in the region. Thereafter, we involved ourselves in the designing and building up of different environments, from casino gaming spaces, indoor firing ranges, lecture halls, recording studios, broadcasting rooms, home theatres, etc. </p> <p> In 2014, we entered Myanmar market. We are slowly gaining momentum in the design & construction industries. </p>';

        $_SESSION['lblFullName']  = 'FULL NAME';
        $_SESSION['lblEmail']  = 'EMAIL';
        $_SESSION['lblSchool']  = 'SCHOOL';
        $_SESSION['lblFaculty']  = 'FACULTY';
        $_SESSION['lblYearStarted']  = 'YEAR STARTED';
        $_SESSION['lblAspiration']  = "WHAT's YOUR CURRENT/FUTURE ASPIRATION";
        $_SESSION['lblSend']  = 'Send';

        $_SESSION['forumdesign_objective_label'] = "International Students' Design Forum";
        $_SESSION['forumdesign_objective_content'] = "<p> The objectives of this design forum is to help build students' confidence in design. <br> We will help them in seeing the physical world in a new realm in order to be more design conscious in problem solving.<br> They will learn through the macro and micro views of components, hence enlarging their perspective in perception in their design concept. </p> <p class='center'> <strong> - When one cannot see beyond the dimensions of life, nothing profitable can be created. - <br> Eric's Haywood Chang's quote </strong> </p> <p> Upon registering with us, students from any design faculty may submit their work for design critics or for discussion.<br> In returned, we will post up these works (after having approval from individual student) for sharing so that more can learn and benefit from it. </p>";
        $_SESSION['forumdesign_contact_label'] = "International Design Student Contact";
        $_SESSION['forumdesign_contact_info'] = "We would like to know you better, kindly help fill in the as below and all information will be confidential.";

        break;
}